
export const languages = [
    { name: 'English', code: 'en' },
    { name: 'हिंदी (Hindi)', code: 'hi' },
    { name: 'தமிழ் (Tamil)', code: 'ta' },
    { name: 'తెలుగు (Telugu)', code: 'te' },
    { name: 'മലയാളം (Malayalam)', code: 'ml' },
    { name: 'ಕನ್ನಡ (Kannada)', code: 'kn' },
    { name: 'मराठी (Marathi)', code: 'mr' },
    { name: 'ગુજરાતી (Gujarati)', code: 'gu' },
    { name: 'বাংলা (Bengali)', code: 'bn' },
    { name: 'ଓଡ଼ିଆ (Odia)', code: 'or' },
    { name: 'ਪੰਜਾਬੀ (Punjabi)', code: 'pa' },
    { name: 'অসমীয়া (Assamese)', code: 'as' },
    { name: 'اردو (Urdu)', code: 'ur' },
    { name: 'कॉशुर (Kashmiri)', code: 'ks' },
    { name: 'कोंकणी (Konkani)', code: 'kok' },
    { name: 'মৈতৈলোন্ (Manipuri)', code: 'mni' },
    { name: 'नेपाली (Nepali)', code: 'ne' },
    { name: 'संस्कृतम् (Sanskrit)', code: 'sa' },
    { name: 'सिन्धी (Sindhi)', code: 'sd' },
    { name: 'मैथिली (Maithili)', code: 'mai' },
    { name: 'बोड़ो (Bodo)', code: 'brx' },
    { name: 'संताली (Santhali)', code: 'sat' },
    { name: 'डोगरी (Dogri)', code: 'doi' },
];
